# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
AMREX_HOME ?= /Users/deanhowarth/2dschwinger_amrex/LatticeAMReX/amrex
ETI_HOME ?= ../..

DEBUG     = FALSE
USE_MPI   = FALSE
USE_OMP   = FALSE

COMP      = clang++
DIM       = 2

USE_SCHWINGER = TRUE
PROBLEM_LOADS_INITDATA = FALSE

include ../Make.ETI
