# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
AMREX_HOME ?= ~/amrex
ETI_HOME ?= ../..

DEBUG     = FALSE
USE_MPI   = TRUE
USE_OMP   = FALSE

COMP      = gnu
DIM       = 2
#TEST = TRUE
#USE_ASSERTION = TRUE
USE_SCHWINGER = TRUE
#DEBUG = TRUE
PROBLEM_LOADS_INITDATA = FALSE

TINY_PROFILE=TRUE

include ../Make.ETI
